# Site settings
title: &page_title
  SmartView
email:
description: SmartView is an agile lean project management and planning tool that combines a story map to manage the backlog with releases and a Kanban board to monitor productivity and status.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.smartviewapp.com" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: rdiscount

sass:
  style: compressed

gems:
  - octopress-image-tag
  - octopress-assign-tag
  - octopress-capture-tag
  - octopress-include-tag
  - octopress-filters
  - jekyll-sitemap

# NOTE: vendor is mandatory to deploy to herkou. See http://www.markcampbell.me/jekyll/heroku/2013/05/18/how-to-set-up-jekyll-on-heroku.html
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'Procfile', 'Rakefile', 'README.md', 'vendor']

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

permalink: /:year/:month/:day/:title/

category:
  prefix: Category
  dir: categories
  url: category
  title: *page_title

rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart

paginate: 4         # Posts per page on the blog index
recent_posts: 5       # Posts in the sidebar Recent Posts section
titlecase: true       # Converts page and post titles to titlecase

destination: public

excerpt_separator: <!-- more -->
excerpt_link: "Read more &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

google_analytics_tracking_id: UA-60154170-1

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
# default_asides: [custom/asides/about.html, asides/recent_posts.html, asides/github.html, asides/twitter.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]
default_asides: [asides/category_list.html]

# ----------------------- #
#    SmartView config     #
# ----------------------- #
smartview:
  app_site: "https://app.smartviewapp.com"
  api_site: "https://smartview-api.herokuapp.com"
